import { BlorboSettings } from "./blorbo";

export const GetDefaultSettings = (): BlorboSettings => ({
  name: "BLORBO BLEEBUS",
  imageDataUrl: null,
  traits: ["Intense", "Fruity", "Complex"].map((name) => ({
    name,
    amount: 0,
  })),
  subclasses: [
    "Angst-lord",
    "Enemy of the State",
    "Flavor Container",
    "Himbo",
    "Soft and Sweet",
    "Braincell Haver",
    "This Is a Kink",
    "Just Like You FR",
    "Chew Toy",
    "Friend-Shaped",
    "Aspirational Character",
    "Little Meow Meow",
  ].map((name) => ({
    name,
    selected: false,
  })),
  addons: [
    "Tragic backstory?",
    "Orphan?",
    "Frequently violent?",
    "Divorced?",
    "Has enemies?",
    "No friends?",
    "Sidekick owner?",
    "Pets stray animals?",
    "Chronic insomniac?",
    "Murderer?",
  ].map((name) => ({
    name,
    selected: false,
  })),
  sliders: [
    {
      negativePole: "just some guy",
      positivePole: "the protagonist of life",
      amount: null,
    },
    {
      negativePole: "head empty",
      positivePole: "too many thoughts",
      amount: null,
    },
    {
      negativePole: "awful company",
      positivePole: "ray of sunshine",
      amount: null,
    },
    {
      negativePole: "hated by all",
      positivePole: "beloved by all",
      amount: null,
    },
    {
      negativePole: "trauma x1000",
      positivePole: "untouched by history",
      amount: null,
    },
    {
      negativePole: "sadistic for fun",
      positivePole: "helps others for fun",
      amount: null,
    },
    {
      negativePole: "stupid as shit",
      positivePole: "scary-smart",
      amount: null,
    },
    {
      negativePole: "1,000 weapons",
      positivePole: "1,000 tools",
      amount: null,
    },
    {
      negativePole: "enemy of god",
      positivePole: "at peace with life",
      amount: null,
    },
    {
      negativePole: "break the rules",
      positivePole: "change the rules",
      amount: null,
    },
  ],
  evokes: [
    "spontaneous gushing",
    "powerful violent urges",
    "raw, unbridled affection",
    "The Horny",
    "late-night thoughts",
    "meta-posting on main",
    "creative drive",
    "defensive feelings",
    "distraction",
    "delight",
    "symptoms of projection",
    "absent-minded doodles on tabletops",
    "the most godawful hot takes known to mankind",
  ].map((name) => ({
    name,
    selected: false,
  })),
  wantThemToHave: [
    "a better time",
    "a worse time",
    "more trauma",
    "less trauma",
    "more romance",
    "less romance",
    "different romance",
    "more friends",
    "painful isolation",
    "a family",
    "catharsis",
    "revenge",
    "sympathy",
    "a better situation",
    "a worse situation",
    "more healing",
    "less healing",
    "more sex",
    "less sex",
    "different sex",
    "different friends",
    "freedom",
    "justification",
    "The Realization™",
    "consequences",
    "a satisfying ending",
  ].map((name) => ({
    name,
    selected: false,
  })),
});
